bosses:
  DevilChan:
    basic:
      - devilish_stab
      - 10
    columns: 4
    energy: 3
    hp: 50
    name: Devil Chan
    phrases:
      attack:
        - For My Lost Love!
        - World Shaking Explosion Fist!
        - North Star Spear!
        - Million Soul Bomb!
        - Burning Sun Beam!
        - Point Two Electron Volts!
      death:
        - NOOOOOOO!!!
        - THIS IS BLASPHEMYYYYYY!!! *dies*
      opening:
        - Angel Chan... I loved you!
        - How could you do this!?
      special:
        - That's a neat little hack that I found.
        - With this hack, I'll steal your health for myself.
        - I hope you're prepared for this.
        - You know, I'm something of a scientist myself.
    rows: 3
    special:
      - neat_hack
      - 10
      - 10
  MrPhone:
    basic:
      - disappointment
      - 0
    columns: 4
    energy: 5
    hp: 200
    kill:
      - thinking_question
      - 9999
    name: Mr. Phone
    phrases:
      attack:
        - You need to touch grass.
        - My son could beat you at this game.
        - Easy choices hard life, hard choices easy life.
        - It's only awkward if you make it awkward.
        - You have to build capacity.
        - You chose that? Come on, that's crazy talk!!!
      death:
        - Huh.
        - Looks like you did practice perfectly.
        - Welp, I'll be on my way then.
        - '*leaves*'
      kill:
        - Next time, just practice perfectly.
        - My record just increased :p
      opening:
        - Did you write your TQP?
      special:
        - Almost everything is a choice... including breathing!
        - Reflect, reflect, REFLECT HARDER!!!
        - Face the monster... ME!
        - Keep your head on a swivel!
    rows: 7
    special:
      - emotional_damage
      - 0
  MsG:
    basic:
      - roast
      - 15
    columns: 4
    energy: 4
    hp: 100
    name: Ms. G
    phrases:
      attack:
        - For Sean!
        - One of them is a woman, the other has an Indian accent if you're into it.
        - "I'll only give you 100% if you\xE2\u20AC\u2122re one of my favourite students."
        - Do it on Repl.it!!!
        - Don't ask me, use your brain.
        - I have WELHpon *pulls out a meter stick*
      death:
        - why must you use... list comphrehension... *dies*
      opening:
        - Hello Sean!
        - How are you doing?
        - Wait, you're not Sean!
      special:
        - You! Go to Siberia!
        - You deserve to go to Siberia!
          out:
            - You- How did you leave!?
    rows: 5
    special:
      - siberia
      - siberia
player:
  hp: 50
settings:
  audio:
    enable_music: true
    enable_sfx: true
    music_vol: 1.0
    sfx_vol: 1.0
  fps:
    show: false
    30: false
    60: false
    75: false
    165: true
  fullscreen: false
